"init.kin" <-
function(){
setClass("kin", 
representation("dat", 
kinpar = "vector", 
specpar = "list",
seqmod = "logical", 
irf = "logical", 
mirf = "logical", 
reftau = "numeric",
cohcol = "numeric",
measured_irf = "vector", 
convalg = "numeric",
irffun = "character", 
irfpar = "vector",  
cohirf = "vector",
dispmu = "logical", 
dispmufun = "character", 
anipar = "vector",
parmu = "list",
disptau = "logical", 
disptaufun = "character", 
partau = "vector",
fullk = "logical",
kmat = "array", 
jvec = "vector", 
anispec = "list",
ncolc = "vector", 
kinscal = "vector", 
kmatfit = "array", 
cohspec = "list", 
coh = "vector",
wavedep = "logical", 
lambdac = "numeric", 
speckin2 = "list", 
usekin2 = "logical", 
kinpar2 = "vector",
kin2scal = "vector"), 
prototype = list( 
kinpar = vector(), 
seqmod = TRUE, 
irf = FALSE, 
mirf = FALSE, 
measured_irf = vector(),
convalg = 1, 
cohirf = vector(),
irffun = "gaus", 
anispec = list(),
irfpar = vector(),  
dispmu = FALSE, 
dispmufun = "poly", 
parmu = list(),
anipar = vector(), 
disptaufun = "poly", 
reftau = 0,
specpar = list(), 
cohcol = 0,
partau = vector(),
posk = FALSE, 
disptau = FALSE,  
fullk = FALSE,
kmat = array(), 
jvec = vector(), 
ncolc = vector(), 
kinscal = vector(), 
kmatfit = array(), 
cohspec = list(), 
coh = vector(),
wavedep = logical(), 
lambdac = numeric(), 
speckin2 = list(), 
usekin2 = FALSE, 
kinpar2 = vector(),
kin2scal = vector()
 ))
}

