"init.opt" <-
function () 
{
    setClass("opt", 
	representation(writecon = "logical", 
			writespec = "logical", 
			writenormspec = "logical", 
			writefit = "logical", 
			writeclperr = "logical",
			residplot = "logical", 
			plot = "logical", 
			divdrel = "logical", 
			plotkinspec = "logical",
			superimpose = "vector",
			xlab = "character",
			ylab = "character",
			title = "character",
			makeps = "character",
			linrange = "numeric",
			summaryplotrow = "numeric",
			summaryplotcol = "numeric",
			iter = "numeric",
			stderrclp = "logical",
			paropt="list", 
			addest="vector"), 
        prototype = list(writecon = FALSE, 
			writespec = FALSE,
			writenormspec = FALSE,
			writefit = FALSE,
			writeclperr = FALSE, 
			residplot = FALSE, 
			plotkinspec = FALSE,
			plot = TRUE,  
			divdrel = TRUE, 
			superimpose = vector(),
			paropt = list(),
			title = "",
			makeps = "",
			stderrclp = FALSE, 
			summaryplotrow = 4, 
			summaryplotcol = 4,
			linrange = 1,
			iter = 1, 
			addest=vector()))
}

